//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace start28
{
    using System;
    using System.Collections.Generic;
    
    public partial class data
    {
        public int Start_Protocol_id { get; set; }
        public int Participants_id { get; set; }
        public int Finish_Procotol_id { get; set; }
    
        public virtual Finish_Protocol Finish_Protocol { get; set; }
        public virtual Participants Participants { get; set; }
        public virtual Start_Protocol Start_Protocol { get; set; }
    }
}
