//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace start28
{
    using System;
    using System.Collections.Generic;
    
    public partial class Start_Protocol
    {
        public int id { get; set; }
        public Nullable<int> Participants_id { get; set; }
        public System.DateTime Time_start { get; set; }
        public string distance { get; set; }
    
        public virtual Participants Participants { get; set; }
    }
}
